# /etc/nginx/sites-available/bts.conf
server {
  listen 80;
  server_name billetterie-test.belougas.fr;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name billetterie-test.belougas.fr;

  ssl_certificate     /etc/letsencrypt/live/billetterie-test.belougas.fr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/billetterie-test.belougas.fr/privkey.pem;

location /bts/ {
  proxy_set_header Host              $host;
  proxy_set_header X-Real-IP         $remote_addr;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_http_version 1.1;
  proxy_set_header Connection "";

  # ⚠️ TRAILING SLASH ICI = STRIP du préfixe /bts/
  proxy_pass http://127.0.0.1:8080/;

 }

  # éviter des 404 parasites sur le favicon
  location = /favicon.ico { return 204; }
}
